#!/bin/bash -ex

ORGA=agners
TAR_DATE=${TAR_DATE:-$(date +'%Y.%m')}
ARCH=arm32v7

for repo in archlinuxarm-${ARCH} archlinuxarm-${ARCH}:full archlinuxarm-${ARCH}:devel; do
	IFS=: read repo tag <<< $repo
	docker pull ${ORGA}/${repo}:${tag:+$tag-}${TAR_DATE}
	# alias the image with name currenttar instead of actual date to get referenced by static dockerfiles
	docker tag  ${ORGA}/${repo}:${tag:+$tag-}${TAR_DATE} ${ORGA}/${repo}:${tag:+$tag-}currenttar
done
