#!/bin/bash -ex

ORGA=agners
TAR_DATE=${TAR_DATE:-$(date +'%Y.%m')}
ARCH=arm32v7

for repo in archlinuxarm-${ARCH} archlinuxarm-${ARCH}:full archlinuxarm-${ARCH}:devel; do
	IFS=: read repo tag <<< $repo
	docker push ${ORGA}/${repo}:${tag:+$tag-}${TAR_DATE}
	docker push ${ORGA}/${repo}${tag:+:$tag}
	"${GOPATH}/bin/manifest-tool" push from-spec "./manifests/manifest${tag:+-$tag}.yml"
done
